version: '3'

services:
  preprocessing-ws:
    build:
      context: .
      dockerfile: Dockerfile  # If your Dockerfile is named something different, replace it here.
    container_name: 'preprocessing-webservice'
    image: preprocessing-webservice:ci
    environment:
      - PORT=3000
      - ENV=prod
    ports:
      - "3010:3000"
