version: '3'

services:
  preprocessing-ws:
    image: preprocessing-webservice:ci
    container_name: 'preprocessing-webservice'
    environment:
      - PORT=3000
      - ENV=prod
    ports:
    - "3010:3000"