name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghrc.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v3

    - name: Authenticate Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{env.REGISTRY}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v1
      with:
        images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v1
      with:
        context: .
        push: true
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
