name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish the Docker Image
        run: |
          docker build . --tag ghcr.io/joaoguedes01/preprocessing-webservice:latest
          docker run ghcr.io/joaoguedes01/preprocessing-webservice:latest
          docker push ghcr.io/joaoguedes01/preprocessing-webservice:latest
