name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: npx semantic-release

      - name: Authenticate Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Extract release version
        id: version
        run: echo ::set-output name=version::$(npx semantic-release --dry-run | grep "version")
        
      - name: Build and Publish the Docker Image
        run: |
          docker build -t ghcr.io/abi-interoperability-thesis/preprocessing-webservice:${{ steps.version.outputs.version }} .
          docker push ghcr.io/abi-interoperability-thesis/preprocessing-webservice:${{ steps.version.outputs.version }}
        
