name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: tests
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t preprocessing-webservice:ci .

      - name: Stop Existing Container
        run: docker stop preprocessing-webservice || true

      - name: Remove Existing Container
        run: docker rm preprocessing-webservice || true

      - name: Run Docker Container
        run: docker run -d -p 3010:3000 --name preprocessing-webservice preprocessing-webservice:ci
