name: Deploy To Test Env

on:
  push:
    branches: [ "dev" ]
jobs:
  tests:
    runs-on: ["abi-interoperability-ci"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test
  build:
    runs-on: ["abi-interoperability-ci"]
    needs: tests
    if: success()

    steps:
      - name: Build Docker Compose
        run: docker-compose build
      
      - name: Run Docker Compose Up
        run: docker-compose up -d