name: Publish Node.js app to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: actions/setup-docker@v3
        with:
          image: 'docker/buildx:latest'

      - name: Build Docker image
        run: docker buildx build -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} .

      - name: Login to GitHub Packages
        run: docker login ghcr.io -u ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}

      - name: Create GitHub Pages artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: ./public
